services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
        - "3306"
    networks:
      - inception
    restart: always
  
networks:
  inception:
    driver: bridge